### ISSUE TITLE
Follies

### ISSUE THREAD

**Issue by lukasbystricky** [BR903/s-s-van-dine_the-canary-murder-case#2]
I'm guessing the Follies refers to this: https://en.wikipedia.org/wiki/Ziegfeld_Follies?

If that's the case I'm not sure this needs to be tagged as music, since it's not really a stand-alone piece. In context it actually seems more like it's referring to a troupe (e.g. "She had quitted the Follies...")

**Comment by BR903** [comment]
I had taken it to just be a fictional music revue. After consulting that article, though, I agree with you that it does seem to be a thinly-fictionalized version of the Ziegfield Follies specifically.

It's confusing because at different times "Follies" is being used to refer to either the troupe or the performance or both. I asked on the mailing list how to semanticate a musical revue, and was told to tag them as just "se.music", so I did. As a general rule we don't seem to semanticate performances differently from the work itself (e.g. "Hamlet" is marked as a play whether it's referring to a printed text or an individual performance).

**Comment by lukasbystricky** [comment]
Ok that's fine in general then, but in cases where it's referring the the troupe (like in the example I gave), I think the italics should be removed.

**Comment by BR903** [comment]
Okay, I've done my best to follow this distinction.
